### ISSUE TITLE
RepoBee dependency should be `>=` when RepoBee 3.0 releases

### ISSUE THREAD

**Issue by slarse** [repobee/repobee-sanitizer#105]
It's currently pinned in `setup.py` and `requirements/app.txt` (i.e. `==`), but should be `>=3.0.0` when RepoBee 3.0 releases.

**Comment by slarse** [comment]
Ping @tohanss , please sort this out!

**Comment by tohanss** [comment]
Somewhere along the line this was done but its set to `repobee>=3.0.0-beta.1` so ill just remove `beta`

**Comment by slarse** [comment]
Closing as fixed in #117
