### ISSUE TITLE
Can not sanitize simple git repos

### ISSUE THREAD

**Issue by tohanss** [repobee/repobee-sanitizer#112]
Right now, because of how we check if something is a git repo, simply running `git init` on an empty folder and committing some files to it is not enough for `repobee-sanitizer` to recognize the folder as a valid git repo

**Comment by slarse** [comment]
What exactly is the problem? The `check_repo_state` function will pass just fine if you have only a single commit.

**Comment by tohanss** [comment]
I made a repo with git init, but some files in it, and committed. Got an error saying that it was not a proper git repo. I dont know exactly what it said but im guessing it came from the gitpython library

**Comment by slarse** [comment]
I can't reproduce that. Could you give me a step-by-step of what you did?

**Comment by tohanss** [comment]
This works now! I think i must have had a repo without any commits even though I thought i had at the time.
