### ISSUE TITLE
Add usage section

### ISSUE THREAD

**Issue by slarse** [repobee/repobee-sanitizer#120]
There's essentially no information on how to use the plugin (e.g. example invocations to commands).

**Comment by rjglasse** [comment]
Furthermore the `sanitize repo -h` feedback was not so informative on the extra arguments that are required:

```
  --no-commit
  --target-branch TARGET_BRANCH
```

**Comment by rjglasse** [comment]
Just some notes from my first experience to help guide :)

- As much of the work with RepoBee can be done remotely against repos on a template-org, it would be worth mentioning that we should be working within the repo locally (obvious in retrospect, but if you are used to use the template-org, this might be confusing, especially as some commands like `setup` do not like to be called from within a repo with a matching name)
- There needs to be a clear description of where you should be when executing the commands, i.e. have checked out the `solutions` branch and targeting the `master` branch. I successfully nuked the `solutions` branch by getting this wrong the first time :)
