### ISSUE TITLE
Shred command inconsistency

### ISSUE THREAD

**Issue by GlennOlsson** [repobee/repobee-sanitizer#128]
Is the command really `REPOBEE_SANITIZER-SHRED` while the rest are `REPOBEE-...` as found `README.md`? The underscore seems inconsistent. Is this really intentional?

**Comment by slarse** [comment]
Nope, that's wrong in the docs, it's definitely with a hyphen:
https://github.com/repobee/repobee-sanitizer/blob/f322cc9193f7fc67a8e67e81431bb17f21081972/repobee_sanitizer/_syntax.py#L22

**Comment by tohanss** [comment]
Ooopsie, will fix
