### ISSUE TITLE
Allow sanitizer markers to match with - or _

### ISSUE THREAD

**Issue by tohanss** [repobee/repobee-sanitizer#28]
Right now repobee markers look like this:

`REPOBEE-SANTIZIER-BLOCK`

but holding SHIFT while writing this is annoying, so we might want to allow

`REPOBEE_SANITIZER_BLOCK`

**Comment by tohanss** [comment]
Having thought about this, i think we should stick to one or the other

**Comment by slarse** [comment]
Then let's just go with the one that we currently have.
