### ISSUE TITLE
Update to RepoBee v3.0.0-alpha.2 and fix the wonky return value in sanitize-repo

### ISSUE THREAD

**Issue by slarse** [repobee/repobee-sanitizer#72]
In `requirements/app.txt` and `setup.py`, change the `repobee` version number to `3.0.0-alpha.2`.

> **Important:** As we are breaking stuff with the alpha releases, we should pin the version number (use `==3.0.0-alpha.2` instead of `>=`)

Then fix the return value from the sanitize-repo command to return a `plug.Result`, instead of a mapping. The update is described in pr repobee/repobee#482

**Comment by tohanss** [comment]
Sanitize-file command should also be changed to not return a mapping
